build.gradle.kts
I suggest pushing releases from the main branch automatically but keeping an approval requirement for other releases.
---
=> Publish releases from the main branch automatically (JBAI-13816)

README.md
=> Add version badge, add 0.1.0 version to examples, fix quickstart example

README.md
=> Remove no longer needed repository

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/MultipleLLMPromptExecutorIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SimpleAgentIntegrationTest.kt
Re-enabled Google models for integration tests ([JBAI-14111](https://youtrack.jetbrains.com/issue/JBAI-14111)) and added retry mechanism in case of failures on the provider side.
---
---
=> Enable Google models in integration tests + introduce executeWithRetry

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/OllamaClientIntegrationTest.kt
Disabled the flaky Ollama test for now.
---
=> Refactor prompt creation and disable flaky test for Ollama

build.gradle.kts, buildSrc/src/main/kotlin/ai.kotlin.dokka.gradle.kts
- Added a missing module to Dokka dependencies
- Included links to external documentation
Closes #146
---
=> Setup dependencies resolution for Dokka

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/OllamaAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SimpleAgentIntegrationTest.kt
Add a one-shot prompt for Ollama tests.
---
=> Enhance test prompts for Ollama.

prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAILLMClient.kt
Because there can be deployments of OpenAI models outside of the official OpenAI API, e.g. Azure OpenAI, the path of the APIs can vary. This PR makes the chat completions and embeddings api paths configurable.
Issue opened: #183 
Discussion on slack: https://kotlinlang.slack.com/archives/C08SLB97W23/p1748430862443289
---
=> Extend OpenAIClientSettings with chat completions API path and embeddings API path to make it configurable

prompt/prompt-llm/src/commonMain/kotlin/ai/koog/prompt/llm/LLMProvider.kt
=> Make LLM provider not sealed

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/MultipleSystemMessagesPromptIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/TestUtils.kt
---
- [] The pull request has a description of the proposed change
=> Handle GoogleAI 503 errors in test retry logic

agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/feature/AIAgentPipeline.kt, agents/agents-core/src/commonTest/kotlin/ai/koog/agents/core/feature/TestFeature.kt, agents/agents-features/agents-features-event-handler/src/commonMain/kotlin/ai/koog/agents/features/eventHandler/feature/EventHandler.kt, agents/agents-features/agents-features-event-handler/src/jvmTest/kotlin/ai/koog/agents/features/eventHandler/feature/EventHandlerFeatureTest.kt, agents/agents-features/agents-features-memory/src/commonMain/kotlin/ai/koog/agents/memory/feature/AgentMemory.kt, agents/agents-features/agents-features-trace/src/commonMain/kotlin/ai/koog/agents/features/tracing/feature/Tracing.kt, agents/agents-test/src/commonMain/kotlin/ai/koog/agents/testing/feature/TestingFeature.kt, examples/src/main/kotlin/ai/koog/agents/example/features/Logging.kt
This is the first PR in a series of changes to make EventHandler actionable regarding control flow of agent.
Purpose of this particular PR is to introduce InterceptContext and unify intercept methods in using that entity. This PR is also makes massive breaking change for interceptors API, so I would like to merge it sooner than later.
---
=> Intercept context introduction

build.gradle.kts
=> Simplify making releases from `develop` by using 4-numbers scheme

examples/src/main/kotlin/ai/koog/agents/example/calculator/CalculatorTools.kt, examples/src/main/kotlin/ai/koog/agents/example/calculator/OllamaCalculatorExample.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/OllamaAgentIntegrationTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/OllamaClient.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/dto/OllamaModels.kt, prompt/prompt-llm/src/commonMain/kotlin/ai/koog/prompt/llm/OllamaModels.kt
Fixed qwq model id, introduced handling for error responses from Ollama
Also introduced Ollama Calculator example because we dont have such simple example for pretty popular Ollama API
---
=> fixing QWQ model, introduced error handling for error responses in Ollama

prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/dto/OllamaManagementConverters.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/dto/OllamaManagementModels.kt
Fixes #247.
I did not fix #239. I will fix it in another MR once the design for #238 has been defined.
---
=> Support Ollama API 0.9 breaking changes

agents/agents-tools/src/jvmMain/kotlin/ai/koog/agents/core/tools/reflect/util.kt, examples/src/main/kotlin/ai/koog/agents/example/calculator/OllamaCalculatorExample.kt
=> missing tools() for ToolSet

CLAUDE.md, CONTRIBUTING.md, TESTING.md
Added some description of how to run the tests locally when contributing.
---
=> Add testing guidelines in TESTING.md

.gitignore
Ignores the `local.properties` file so devs won't accidentally commit it.
---
=> Git ignore `local.properties`

.github/workflows/checks.yml, .github/workflows/heavy-tests.yml, .github/workflows/ollama-tests.yml
=> Fix `setup-gradle` action caching issue

prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/message/Attachment.kt
=> Don't print content in `AttachmentContent.Binary.Bytes.toString`

prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/message/Attachment.kt
=> Don't print content in `AttachmentContent.Binary.Base64.toString` and `AttachmentContent.PlainText.toString`

prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/dsl/AttachmentBuilder.kt, prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/dsl/PromptBuilder.kt
There are a few outdated attachment usage examples in KDocs, this PR fixes these
=> [prompt] Fix attachments related KDocs

README.md
Fixes #273
---
- [] Tests for the changes have been added
=> Update readme with a link to external dependencies

examples/notebooks/VaccumAgent.ipynb
This PR to fix the broken example VaccumAgent.ipynb as discussed in issue #228 https://github.com/JetBrains/koog/issues/228
---
=> :bug: Fix broken example after removal of simpleChatAgent #228

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SimpleAgentIntegrationTest.kt
Test verifying the bugfix https://github.com/JetBrains/koog/issues/300
---
=> Add integration test for LLM requests without tool usage

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AIAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/TestUtils.kt, prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/message/Message.kt
Added tests for Parallel & Sequential tool calls, and for sequential calls in a single run.
Also, done some renaming, namely `SimpleAgentIntegrationTest` => `AIAgentIntegrationTest`.
---
=> Add integration tests for parallel tool execution in AIAgent.

agents/agents-tools/src/commonTest/kotlin/ai/koog/agents/core/tools/serialization/ToolComplexParameterTypesTest.kt
Adding tests for execution of tools with complex params structure, such as:
- objects
- objects with additional properties ("open" type of parameter)
- lists: of enums, of objects, nested
---
=> Add tests for tool execution of tools with complex parameters.

agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/builder/AIAgentEdgeBuilder.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/builder/AIAgentNodeBuilder.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/builder/AIAgentSubgraphBuilder.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/builder/BaseBuilder.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/extension/AIAgentEdges.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/extension/AIAgentNodes.kt, agents/agents-ext/src/commonMain/kotlin/ai/koog/agents/ext/agent/AIAgentSubgraphExt.kt, agents/agents-features/agents-features-memory/src/commonMain/kotlin/ai/koog/agents/memory/feature/nodes/MemoryNodes.kt
- Annotated methods with @AIAgentBuilderDslMarker for consistent DSL highlighting
- Renamed the @AIAgentBuilderMarker annotation to @AIAgentBuilderDslMarker since the color currently depends on its name
- Added @EdgeTransformationDslMarker for proper edge operations highlighting
---
=> Improved DSL highlighting

agents/agents-ext/src/commonTest/kotlin/ai/koog/agents/ext/agent/AIAgentStrategiesTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AIAgentIntegrationTest.kt
1. Added basic tests for AIAgentStrategies constructors;
2. Added an integration test for an agent with the ReAct strategy;
3. Made a small refactoring: fixed test names, removed useless stdout steps from the event handler.
---
=> ReAct subgraph tests

agents/agents-features/agents-features-opentelemetry/build.gradle.kts, examples/src/main/kotlin/ai/koog/agents/example/features/opentelemetry/OpenTelemetry.kt
=> JBAI-14524. Update dependencies for Open Telemetry module

build.gradle.kts
=> Add missing rag-base, vector-storage, and bedrock to Dokka modules

agents/agents-utils/src/wasmJsMain/kotlin/ai/koog/agents/utils/Coroutines.wasmJs.kt, koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/KoogAutoConfig.kt, koog-spring-boot-starter/src/main/kotlin/ai/koog/spring/KoogProperties.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/BedrockModelFamilies.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/BedrockToolSerialization.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/BedrockAI21JambaSerialization.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/JambaDataModel.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/amazon/BedrockAmazonNovaSerialization.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/amazon/NovaDataModels.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/anthropic/BedrockAnthropicClaudeSerialization.kt, prompt/prompt-executor/prompt-executor-clients/src/commonMain/kotlin/ai/koog/prompt/executor/clients/InternalLLMClientApi.kt
Add missing KDocs for Spring integration
---
=> Add missing KDocs for Spring integration

examples/build.gradle.kts, examples/src/main/kotlin/ai/koog/agents/example/snapshot/SnapshotStrategy.kt, integration-tests/build.gradle.kts, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AIAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/MultipleLLMPromptExecutorIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SingleLLMPromptExecutorIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/Models.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-google-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/google/GoogleModels.kt
- add tests for checkpoints & persistency
- fix infinite loop in SnapshotStrategy.
---
=> Agent Checkpoints tests

CHANGELOG.md, README.md, build.gradle.kts, examples/demo-android-app/app/build.gradle.kts, examples/demo-android-app/app/src/main/java/com/jetbrains/example/kotlin_agents_demo_app/agents/calculator/CalculatorAgentProvider.kt, examples/demo-android-app/app/src/main/java/com/jetbrains/example/kotlin_agents_demo_app/agents/calculator/CalculatorTools.kt, examples/demo-android-app/app/src/main/java/com/jetbrains/example/kotlin_agents_demo_app/agents/common/AgentProvider.kt, examples/demo-android-app/app/src/main/java/com/jetbrains/example/kotlin_agents_demo_app/agents/common/ExitTool.kt, examples/demo-android-app/app/src/main/java/com/jetbrains/example/kotlin_agents_demo_app/agents/weather/WeatherAgentProvider.kt, examples/demo-android-app/app/src/main/java/com/jetbrains/example/kotlin_agents_demo_app/agents/weather/WeatherTools.kt, examples/demo-android-app/app/src/main/java/com/jetbrains/example/kotlin_agents_demo_app/screens/agentdemo/AgentDemoViewModel.kt, examples/demo-android-app/gradle/libs.versions.toml, examples/demo-android-app/settings.gradle.kts, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/meta/BedrockMetaLlamaSerialization.kt
Update version to `0.3.0` and add change log
---
=> 0.3.0 Koog release

buildSrc/src/main/kotlin/ai.kotlin.jvm.publish.gradle.kts, buildSrc/src/main/kotlin/ai/koog/gradle/publish/maven/Publishing.kt
=> add javadoc artifact in Maven publishing configuration

.github/workflows/heavy-tests.yml
https://jetbrains.slack.com/archives/C05JY4RF41J/p1752145137809289
---
=> Fix AWS Bedrock tests connection

buildSrc/src/main/kotlin/ai.kotlin.jvm.publish.gradle.kts
Refactor kotlin.jvm script to simplify adding javadoc
---
=> Simplify Javadoc jar creation in kotlin jvm script

CONTRIBUTING.md, README.md, docs/overrides/partials/header.html
=> Add link to KG tracker to readme & docs header

agents/agents-features/agents-features-common/src/jvmTest/kotlin/ai/koog/agents/features/remote/server/FeatureMessageRemoteServerTest.kt, agents/agents-features/agents-features-common/src/jvmTest/kotlin/ai/koog/agents/features/writer/FeatureMessageRemoteWriterTest.kt, agents/agents-features/agents-features-trace/src/jvmTest/kotlin/ai/koog/agents/features/tracing/writer/TraceFeatureMessageRemoteWriterTest.kt
=> KG-174. Fix failures for remote writer tests caused by timeout

agents/agents-features/agents-features-opentelemetry/README.md, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryConfig.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryTest.kt
https://youtrack.jetbrains.com/issue/KG-169/Add-support-for-setting-the-OpenTelemetry-SDK-in-koog
=> KG-169. Add support for setting the OpenTelemetry SDK in koog

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/OllamaExecutorIntegrationTest.kt
=> Unmute "ollama_test execute streaming API with structured data"

.github/workflows/checks.yml, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryConfig.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/OllamaExecutorIntegrationTest.kt
Add `ktlintCheck` call to verify formatting
---
=> Add ktlintCheck to checks workflow

prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/params/LLMParams.kt, prompt/prompt-model/src/jvmTest/kotlin/ai/koog/prompt/PromptTest.kt, prompt/prompt-model/src/jvmTest/kotlin/ai/koog/prompt/params/LLMParamsTest.kt
- Added tests for the LLMParams
- Added validation for param values on the constructor level
---
=> Add input validation and corresponding tests to LLMParams

examples/src/main/kotlin/ai/koog/agents/example/guesser/NumberGuessingAgent.kt
---
- Fix NumberGuessingAgent Example
- Added the **SayToUser Tool**. (discussed in https://github.com/JetBrains/koog/issues/355)
- Included an extra condition in the prompt because I found the system wasn't successfully handling cases like 75.
Let's assume I thought of 75.
```
Agent says: Please think of a number between 1 and 100.
Is your number less than 50? [Y/n]: n
Is your number greater than 50? [Y/n]: y
Is your number less than 75? [Y/n]: n
Is your number greater than 75? [Y/n]: n
Is your number less than 88? [Y/n]: y
Is your number greater than 81? [Y/n]: n
Is your number equal to 81? [Y/n]: n
Is your number equal to 82? [Y/n]: n
Is your number equal to 83? [Y/n]: 
...
```
If it's not less than 75 and not greater than 75, the answer is 75.
But the agent is asking the wrong …
=> KG-101. Fix NumberGuessingAgent Example

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AIAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/MultipleLLMPromptExecutorIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SingleLLMPromptExecutorIntegrationTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-anthropic-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/anthropic/AnthropicModels.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-google-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/google/GoogleModels.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAIModels.kt
- Temporarily disable AWS Bedrock executor integration tests
- Remove Documentation capability from Google models
- Some refactorings
---
=> Fix integration tests run

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AIAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SingleLLMPromptExecutorIntegrationTest.kt
=> Integration tests stabilization

build.gradle.kts, docs/README.md, docs/build.gradle.kts
Add clean task for knit
Exclude docs from kover
---
=> Knit clean task

rag/rag-base/src/jvmMain/kotlin/ai/koog/rag/base/files/JVMFileSystemProvider.kt
=> Move suspendable operations to Dispatchers.IO context

rag/rag-base/src/commonMain/kotlin/ai/koog/rag/base/files/FileSystemProvider.kt, rag/rag-base/src/commonMain/kotlin/ai/koog/rag/base/files/FilteredFileSystemProvider.kt, rag/rag-base/src/jvmMain/kotlin/ai/koog/rag/base/files/JVMFileSystemProvider.kt, rag/vector-storage/src/commonTest/kotlin/ai/koog/rag/vector/mocks/MockDocumentProviders.kt
=> Remove deprecated methods from FileSystemProvider

docs/mkdocs.yml
Fixes #548 and [KG-221](https://youtrack.jetbrains.com/issue/KG-221)
Users will be able to make some drive-by improvements of the docs.
None
---
=> KG-221 Add an edit button to the docs

agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/integration/langfuse/Langfuse.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/integration/langfuse/LangfuseSpanAdapter.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/integration/weave/Weave.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/integration/weave/WeaveSpanAdapter.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/integration/langfuse/LangfuseTraceStructureTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/integration/weave/WeaveTraceStructureTest.kt
See [KG-266](https://youtrack.jetbrains.com/issue/KG-266) Function call parameters are always hidden.
No.
---
=> KG-266 Remove verbosity configuration from adapters

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AIAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AnthropicSchemaValidationIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/RetryUtils.kt
Fixes to avoid heavy tests' failures that aren't related to the real bugs.
- Refactor test lifecycle methods to cleanUp/setup conventions (to avoid overlapping of counters during parallel execution);
- Add `Retry` annotation to `integration_testAnthropicComplexNestedStructures`;
- Update RetryUtils with additional error case handling for 3-rd party OpenAI error;
- Add more iterations to the ReAct agent tests (execution is expected to take more steps after adding the feedback mechanism to the strategy).
None.
---
=> Fix failing heavy tests

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AIAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/OllamaAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/annotations/RetryExtension.kt
- Replaced `rewritePrompt` with `updatePrompt` in tests (so the old prompt and context is passed between stages and isn't completely rewritten);
- Increased max iterations from `15` to `20` steps;
- Improved retry logic in `RetryExtension` with direct test method invocation on multiple attempts (fixing `Chain of InvocationInterceptors called invocation multiple times instead of just once` exception thrown by JUnit on retries);
- Replaced `runBlocking()` with `runTest()` in `AIAgentIntegrationTest` to avoid race conditions.
None.
---
=> Fix OllamaAgentIntegrationTest and AIAgentIntegrationTest

agents/agents-features/agents-features-debugger/src/jvmTest/kotlin/ai/koog/agents/features/debugger/feature/DebuggerTest.kt
=> Update the nr of expected events in debugger tests

docs/docs/tools-overview.md
Add documentation for agent as tool
Fixes: https://youtrack.jetbrains.com/issue/KG-242/Add-docs-for-Agent-as-Tool
---
=> Add documentation for agent as tool

docs/docs/opentelemetry-support.md
[KG-290](https://youtrack.jetbrains.com/issue/KG-290). Update documentation about OpenTelemetry feature with new capabilities and integrations (Langfuse/Weave).
Updated documentation.
---
=> [WIP] KG-290. Update OpenTelemetry feature documentation with Langfuse/Weave integrations

docs/docs/ktor-plugin.md, docs/mkdocs.yml
=> Add ktor integration documentation

.github/CODEOWNERS
=> Update CODEOWNERS for rag-base classes

.github/CODEOWNERS
=> Add Egor as a code owner for FSP, filtered-FSP and JVM-FSP

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/MultipleLLMPromptExecutorIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SingleLLMPromptExecutorIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/TestUtils.kt, prompt/prompt-structure/src/commonTest/kotlin/ai/koog/prompt/structure/json/JsonStructuredDataTest.kt
Tests for [KG-100](https://youtrack.jetbrains.com/issue/KG-100) Json Schema / Response Schema Support.
- Added native structured JSON output test for single/multiple LLM executors;
- Added `JsonStructuredDataTest` for unit testing of JSON structure generation and parsing.
None.
---
=> JSON structured output tests

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AIAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/AIAgentMultipleLLMIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/MultipleLLMPromptExecutorIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SingleLLMPromptExecutorIntegrationTest.kt
Exclude flaky profiles from the run and add retries
None.
---
=> Exclude flaky profiles from the run and add retries

CHANGELOG.md, README.md, build.gradle.kts
=> 0.4.0 release

.github/workflows/push-to-main.yml
=> mkdocs force deploy

docs/docs/examples/Attachments.md, docs/docs/examples/Banking.md, docs/docs/examples/BedrockAgent.md, docs/docs/examples/Calculator.md, docs/docs/examples/Chess.md, docs/docs/examples/GoogleMapsMcp.md, docs/docs/examples/Guesser.md, docs/docs/examples/Langfuse.md, docs/docs/examples/OpenTelemetry.md, docs/docs/examples/PlaywrightMcp.md, docs/docs/examples/UnityMcp.md, docs/docs/examples/VaccumAgent.md, docs/docs/examples/Weave.md
=> Add missing `notebooks` word to example links

docs/README.md, docs/docs/agent-memory.md, docs/docs/complex-workflow-agents.md, docs/docs/index.md, docs/docs/prompt-api.md, docs/docs/tools-overview.md
- Replace inconsistent list formats with manual numbering where required for KNIT compatibility
- Add a note to README.md about using manual numbering
- Add missing LLM providers and LLM clients and link to related documentation
---
=> Add missing LLM providers and clients, add iOS target, fix KNIT list compatibility, update README with manual numbering note

prompt/prompt-executor/prompt-executor-clients/prompt-executor-deepseek-client/src/jvmTest/kotlin/deepseek/DeepSeekLLMClientTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-model/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/models/OpenAIDataModels.kt
Make audioTokens optional for in usages data
Add missed mkdocs
Fixes: https://github.com/JetBrains/koog/issues/676
---
=> Fix usages in OpenAI based data model

docs/docs/agent-memory.md
=> Fix code example in agent-memory documentation

koog-agents/build.gradle.kts, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/build.gradle.kts, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/BedrockAI21JambaSerialization.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/JambaDataModel.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/BedrockAI21JambaSerializationTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/JambaDataModelsTest.kt, settings.gradle.kts, test-utils/build.gradle.kts, test-utils/gradle.properties, test-utils/src/commonMain/kotlin/ai/koog/test/utils/SerializationHelpers.kt, test-utils/src/commonTest/kotlin/ai/koog/test/utils/SerializationHelpersTest.kt
Provide helper classes for serialization checks, e.g. for #668 
- Added a new `test-utils` module for shared testing utilities.
- Implemented `verifyDeserialization` helper to simplify validation of JSON payloads.
- Refactored serialization tests in `JambaDataModelsTest` to use `verifyDeserialization`.
- Updated build configurations to include `test-utils` as a dependency.
- Removed redundant logger declaration from `BedrockAI21JambaSerialization`.
- **Bugfix:** Added `@EncodeDefault` annotation in `JambaToolCall` for default property encoding.
---
=> Introduce test-utils module and refactor serialization tests

agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/integration/TraceStructureTestBase.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/integration/langfuse/LangfuseTraceStructureTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/integration/weave/WeaveTraceStructureTest.kt
The tests are mostly checking basic things and are used for manual testing. Proper coverage will be provided by integration tests.
1. `testSubgraphWithFinishTool` is passing since it doesn't make sense to write a comprehensive test until subgraph traces are properly supported.
2. `testContentModerationEventOnLLMSpan` and `testEmbeddingsTracingWithOpenAI` are currently disabled as moderation and embeddings tracing aren't supported. The tests are mentioned in the corresponding tickets to make sure they are enabled once the issues are fixed.
---
=> Add tracing tests

docs/docs/why-koog.md, docs/mkdocs.yml
=> Add Why Koog page to documentation

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/Models.kt, koog-ktor/src/commonMain/kotlin/ai/koog/ktor/utils/LLMModelParser.kt, koog-ktor/src/commonTest/kotlin/ai/koog/ktor/ModelIdentifierParsingTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-anthropic-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/anthropic/AnthropicModels.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/BedrockModels.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/BedrockLLMClientTest.kt
Add missing model to AnthropicModels and BedrockModels. Create unit tests.
This PR fixes the [missing model issue](https://github.com/JetBrains/koog/issues/729). Opus 4.1 is identical to Opus 4.0, so no compatibility issues should be introduced.
No
---
=> Add Claude Opus 4.1 model support

CONTRIBUTING.md
Add prerequisites how to build locally
Provide cleaner instructions how to build the project
---
=> Update build prerequisites (CONTRIBUTING.md)

.github/workflows/heavy-tests.yml
Fix parallelised tests naming
---
=> Add job names to heavy-tests workflow 

README.md
Add GitHub Actions build status badges to README.md for visibility
Failing tests should be visible. Let's embrace "Perfection through the pain!"
---
=> Add GitHub Actions build status badges to README.md for visibility

prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/Module.md, prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAIModels.kt
add the new gpt-audio model for OpenAI. It's a general model for audio inputs and outputs 
No
---
=> Add `GptAudio` model in OpenAI client

agents/agents-features/agents-features-snapshot/src/commonMain/kotlin/ai/koog/agents/snapshot/feature/Persistency.kt, agents/agents-features/agents-features-snapshot/src/jvmTest/kotlin/PersistencyRestoreStrategyTests.kt
=> Fix automatic persistency MessageOnly strategy restore

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/agent/AIAgentIntegrationTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-anthropic-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/anthropic/AnthropicLLMClient.kt
[KG-317](https://youtrack.jetbrains.com/issue/KG-317) Do not require a system prompt
---
=> KG-317: Do not include an empty system message in Anthropic request

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/executor/ToolDescriptorIntegrationTest.kt
As a follow-up to our last week discussion, it's good to test different input/output combinations in tool descriptors after the merge of #791.
None.
---
=> Add integration tests for executing tools with primitive types combinations

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/agent/AIAgentIntegrationTest.kt
Fix final messages collection in integration test for history compression
---
=> Fix compress history integration test
