integration-tests/src/jvmTest/kotlin/ai/jetbrains/code/integration/tests/SimpleAgentIntegrationTest.kt
Enabled `SimpleAgentIntegrationTest` after bugfixed from the framework side.
---
=> Enable SimpleAgentIntegrationTest for all models except for o1

integration-tests/src/jvmTest/kotlin/ai/jetbrains/code/integration/tests/KotlinAIAgentWithMultipleLLMIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/jetbrains/code/integration/tests/MultipleLLMPromptExecutorIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/jetbrains/code/integration/tests/MultipleSystemMessagesPromptIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/jetbrains/code/integration/tests/OllamaAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/jetbrains/code/integration/tests/OllamaClientIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/jetbrains/code/integration/tests/OpenAIEmbeddingsIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/jetbrains/code/integration/tests/OpenRouterLLMClientIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/jetbrains/code/integration/tests/SimpleAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/jetbrains/code/integration/tests/tools/AnswerVerificationTool.kt, integration-tests/src/jvmTest/kotlin/ai/jetbrains/code/integration/tests/tools/GenericParameterTool.kt, integration-tests/src/jvmTest/kotlin/ai/jetbrains/code/integration/tests/tools/GeographyQueryTool.kt, integration-tests/src/jvmTest/kotlin/ai/jetbrains/code/integration/tests/utils/Models.kt, integration-tests/src/jvmTest/kotlin/ai/jetbrains/code/integration/tests/utils/TestLogger.kt, integration-tests/src/jvmTest/kotlin/ai/jetbrains/code/integration/tests/utils/TestUtils.kt
Refactor integration tests package structure for better modularity. Now `utils` is a module that contains test utils, and `tools` is a module that contains tools used in the tests.
---
=> Refactor integration tests package structure

prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/OllamaClient.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/OllamaModelFactory.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/OllamaModelManager.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/OllamaModelResolver.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/OllamaModelUtils.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/dto/OllamaConverters.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/client/dto/OllamaManagementModels.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonTest/kotlin/ai/koog/prompt/executor/ollama/client/OllamaToolCallTest.kt
This pull request introduces significant enhancements to the `OllamaClient` and its associated components, enabling dynamic model management and improving the flexibility of interacting with the Ollama API. The most notable changes include adding support for dynamic model resolution, introducing a new `OllamaModelFactory` for creating models, and implementing a `OllamaModelManager` for managing model discovery and capabilities. These changes collectively enhance the modularity and extensibility of the Ollama client.
* Added support for dynamic model resolution via the `enableDynamicModels` property, allowing models to be resolved dynamically using the `OllamaModelResolver`. This impacts methods like `execute`, `stream`, and `embed`, which now use dynamically resolved model names.
* …
=> Add dynamic model discovery and fix tool call IDs for Ollama client

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/MultipleLLMPromptExecutorIntegrationTest.kt
Default timeout is 1 minute, which is not enough for some tests.
---
=> Set timeout for MultipleLLMPromptExecutorIntegrationTest integration tests to 300 seconds

gradle/libs.versions.toml, integration-tests/build.gradle.kts, integration-tests/src/jvmTest/resources/simplelogger.properties, prompt/prompt-executor/prompt-executor-llms-all/build.gradle.kts, prompt/prompt-executor/prompt-executor-llms-all/src/jvmTest/resources/simplelogger.properties
- Added SLF4J Simple as a test runtime dependency in relevant Gradle modules with jvmTests sourceSets.
- Included default `simplelogger.properties` with custom log level and formatting settings for testing environments.
---
=> Add SLF4J Simple logger to tests

README.md
The link to the Slack channel for support in the README requires being logged in to the Slack workspace already which requires an invite or having an `@jetbrains` email.
This PR updates the link to point to the publicly accessible readonly version of the Slack workspace, which also includes a link for how to request to join.
It also follows the same link used in CONTRIBUTING.md to be consistent
Triggered by https://github.com/JetBrains/koog/issues/166
---
=> Link to the publicly viewable slack channel in the README

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/OllamaSimpleAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SimpleAgentIntegrationTest.kt
Isolated Ollama test because apparently the integration tests were failing because of the test fixture initialization on Windows. However, I didn't want to exclude the whole class from the Windows run.
---
=> Isolate Ollama integration test logic

.github/workflows/heavy-tests.yml, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/OllamaAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/OllamaClientIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/OllamaSimpleAgentIntegrationTest.kt
As Ollama tests are quite unstable, and the supposed reason is that they are interfering with each other while running in parallel.
I'll try to make them run sequentially. If it helps, the next step will be separating Ollama tests into another test configuration (and run them sequentially while tests for other executors are still running in parallel).
---
=> Enable Mac support for tests and adjust Gradle test execution to run without parallelism

prompt/prompt-llm/src/commonMain/kotlin/ai/koog/prompt/llm/OllamaModels.kt
Added new predefined models LLAMA_3_GROK_TOOL_USE, LLAMA_3_2_3B (not sure if the LLAMA_3_2 is the 3B params), QWEN_2_5_05B, and QWEN_3_06B under their respective providers. All models with capabilities such as temperature adjustment, simplified and full JSON schema support (even if the Grok model was not clear about it), and tool utilization.
I opened the issue here: https://github.com/JetBrains/koog/issues/154
---
=> Add new LLM configurations for Groq, Meta, and Alibaba

examples/src/main/kotlin/ai/koog/agents/example/ApiKeyService.kt
The examples use `ai.koog.agents.example.ApiKeyService` to pull model keys from environment variables. When open ai isn't found, you get an exception with 'OPENAI_API_KEY env is not set'. It took some extra time to debug because 'OPENAI_API_KEY' isn't actually the name of the value that `ApiKeyService` is looking for, but 'OPEN_AI_TOKEN'.
Since other docs use 'OPENAI_API_KEY', I figured that was the convention to use. If somebody has the examples currently running with 'OPEN_AI_TOKEN', the change will break that, but it seems more consistent to use 'OPENAI_API_KEY'.
---
=> Change OPEN_AI_TOKEN to OPENAI_API_KEY

agents/agents-mcp/Module.md, agents/agents-mcp/src/jvmMain/kotlin/ai/koog/agents/mcp/McpToolDefinitionParser.kt, agents/agents-mcp/src/jvmMain/kotlin/ai/koog/agents/mcp/McpToolRegistryProvider.kt, agents/agents-mcp/src/jvmTest/kotlin/ai/koog/agents/mcp/DefaultMcpToolDescriptorParserTest.kt, agents/agents-tools/src/commonMain/kotlin/ai/koog/agents/core/tools/ToolDescriptors.kt, examples/src/main/kotlin/ai/koog/agents/example/mcp/GoogleMapsMcpClient.kt, examples/src/main/kotlin/ai/koog/agents/example/mcp/UnityMcpAgent.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/OpenAILLMClient.kt
One more step to cover all possible arg types for the MCP tools
- Support enum arg type parsing
- Support object additionalParameters flag with types/bool parsing
- Add try/catch wrapper to skip tools which we are not able to parse for now
- Add MCP docs
Resolves part of the https://github.com/JetBrains/koog/issues/233
=> MCP proper object and enum arg types support

prompt/prompt-structure/src/commonMain/kotlin/ai/koog/prompt/structure/StructureParser.kt
Fixes the grammar and adds missing punctuation in the `code-engine-structure-fixing` prompt. 
---
=> Fix grammar and punctuation in StructureParser prompt 

agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/feature/remote/server/config/AIAgentFeatureServerConnectionConfig.kt, agents/agents-features/agents-features-common/src/commonMain/kotlin/ai/koog/agents/features/common/remote/server/FeatureMessageRemoteServer.kt, agents/agents-features/agents-features-common/src/commonMain/kotlin/ai/koog/agents/features/common/remote/server/config/ServerConnectionConfig.kt, agents/agents-features/agents-features-trace/src/jvmTest/kotlin/ai/koog/agents/features/tracing/writer/TraceFeatureMessageRemoteWriterTest.kt
✅ What: Added host property to ServerConnectionConfig
✅ Why: To allow proper host configuration for FeatureMessageRemoteServer
✅ Type: Fix addresses the 127.0.0.1 binding issue
---
=> Fix - Allow host config for FeatureMessageRemoteServer 

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/MultipleLLMPromptExecutorIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/MultipleSystemMessagesPromptIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/OllamaAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/OllamaSimpleAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SimpleAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SingleLLMPromptExecutorIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/RetryUtils.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/annotations/Retry.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/annotations/RetryExtension.kt
Implements #242
Skipping OpenAI audio models in streaming tests in `MultipleLLMPromptExecutorIntegrationTest`.
---
=> Skip OpenAI audio models in streaming integration tests in MultipleLLMPromptExecutorIntegrationTest

agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/session/AIAgentLLMSession.kt
Fixes #267 to properly support LLM requests without tools across all LLM providers
=> [agent] fix requestLLMWithoutTools to work properly across all providers

agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/entity/AIAgentStorage.kt, agents/agents-ext/src/commonMain/kotlin/ai/koog/agents/ext/agent/AIAgentSubgraphExt.kt, agents/agents-test/src/commonMain/kotlin/ai/koog/agents/testing/tools/MockLLMBuilder.kt, examples/build.gradle.kts, examples/src/main/kotlin/ai/koog/agents/example/banking/routing/RoutingViaGraph.kt, examples/src/main/kotlin/ai/koog/agents/example/mcp/UnityMcpAgent.kt, examples/src/main/kotlin/ai/koog/agents/example/memory/CustomerSupportAgent.kt, examples/src/main/kotlin/ai/koog/agents/example/subgraphwithtask/CustomStrategy.kt, examples/src/main/kotlin/ai/koog/agents/example/subgraphwithtask/ProjectGenerator.kt, examples/src/test/kotlin/ai/koog/agents/example/memory/CustomerSupportTest.kt
* Refactor the implementation of `subgraphWithTask` to make the code more readable 
* Don't make a task message `system`, it's just a `user` message now
* Remove built-in complicated message history handling logic, make the whole process more straightforward to avoid non-obvious side-effects 
* It's mandatory now to add your `finishTool` to the global agent tool registry, since it is actually executed now as a regular tool
* Also, turns it `onRequestContains` in `MockLLMBuilder` for mocking tool calls was missing, which was required to adjust tests in this PR. So I added it as well
=> [agent] Refactor subgraph with task. Simplify message handling to make it more straightforward and easier to use.

agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/session/AIAgentLLMSession.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/environment/SafeTool.kt, agents/agents-ext/src/commonMain/kotlin/ai/koog/agents/ext/agent/AIAgentSubgraphExt.kt, prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/dsl/PromptBuilder.kt
* Properly handle tools in history when calling request structured
* Append `finishTool` result in zsubgraphWithTask` to prompt, otherwise subsequent LLM calls fail
* Undeprecate `result` and `call` `PromptBuilder` methods
=> [agent] [prompt] Fixes: structured LLM request, subgraphWithTask. Undeprecate PromptBuilder methods

prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonMain/kotlin/ai/koog/prompt/executor/ollama/tools/json/JSONSchemaFunctionConverter.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-ollama-client/src/commonTest/kotlin/ai/koog/prompt/executor/ollama/client/JSONSchemaFunctionConverterTest.kt
There was a problem with Ollama function schema generation from `ToolDescriptor`: some fields and descriptions were not processed correctly and therefore were missing from the resulting function JSON schema.
=> [prompt] Fix Ollama function schema generation

prompt/prompt-structure/src/commonMain/kotlin/ai/koog/prompt/structure/json/JsonStructuredData.kt, prompt/prompt-structure/src/commonTest/kotlin/ai/koog/prompt/structure/StructuredDataTest.kt
Fixed an issue where structured data examples were prompted wrong.
---
The LLM was always prompted "Here are the examples of valid responses:" even if there were no examples provided or if only one example was provided.
=> Fixed an issue where structured data examples were prompted wrong

agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/AIAgentException.kt, agents/agents-test/src/jvmTest/kotlin/ai/koog/agents/test/AIAgentExceptionTest.kt
Fixes #293 ai.koog.agents.core.agent.AIAgentException should be Exception, not Throwable
---
=> #293 Refactor `AIAgentException` and add unit tests

agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/context/AIAgentContext.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/context/AIAgentContextBase.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/context/AIAgentLLMContext.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/entity/AIAgentSubgraph.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/builder/AIAgentParallelNodesMergeContext.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/builder/AIAgentSubgraphBuilder.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/extension/AIAgentNodes.kt, agents/agents-core/src/commonTest/kotlin/ai/koog/agents/core/feature/AIAgentPipelineTest.kt, agents/agents-ext/src/commonMain/kotlin/ai/koog/agents/ext/agent/AIAgentSubgraphExt.kt, agents/agents-test/src/commonMain/kotlin/ai/koog/agents/testing/feature/TestingFeature.kt, agents/agents-test/src/commonMain/kotlin/ai/koog/agents/testing/tools/DummyAIAgentContext.kt, examples/src/main/kotlin/ai/koog/agents/example/banking/routing/RoutingViaGraph.kt, examples/src/main/kotlin/ai/koog/agents/example/subgraphwithtask/CustomStrategy.kt
Support settings custom `LLModel` and `LLMParams` overrides for subgraphs, to allow delegating different tasks to different LLMs with different parameters. 
Fixes #338
=> [agents] Support custom LLModel and LLMParams in subgraphs, make nodeUpdatePrompt a pass-through node

agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/AIAgent.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/AIAgentSimpleStrategies.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/extension/AIAgentEdges.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/extension/AIAgentNodes.kt, agents/agents-core/src/commonTest/kotlin/ai/koog/agents/core/agent/DummyTools.kt, agents/agents-core/src/commonTest/kotlin/ai/koog/agents/core/agent/SingleRunStrategyTests.kt, agents/agents-features/agents-features-snapshot/src/jvmTest/kotlin/SimpleGraphCheckpointTest.kt, agents/agents-test/src/commonMain/kotlin/ai/koog/agents/testing/tools/MockLLMBuilder.kt, agents/agents-test/src/commonMain/kotlin/ai/koog/agents/testing/tools/MockLLMExecutor.kt, agents/agents-test/src/commonTest/kotlin/ai/koog/agents/testing/tools/MockLLMBuilderTests.kt, agents/agents-test/src/jvmTest/kotlin/ai/koog/agents/test/SimpleAgentMockedTest.kt, examples/src/main/kotlin/ai/koog/agents/example/calculator/OllamaCalculatorExample.kt
Modified singleRunStrategy in order to support parallel tools calls.
Also introduced node that calls tools and sends results to back to LLM.
To test it I modified MockLLMExecutor a little bit to support mocking multiresponses.
=> Simple single run strategy working with multiple message

rag/rag-base/src/commonMain/kotlin/ai/koog/rag/base/RankedDocumentStorage.kt
This is a quick fix for `mostRelevantDocuments` as explained in #397.
I also made `mostRelevantDocuments` an extension rather than a final member of `RankedDocumentStorage`.
---
=> Take count into account in mostRelevantDocuments

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/OllamaAgentIntegrationTest.kt
Fix the failing OllamaAgentIntegrationTest by adding necessary extensions via the `@ExtendWith` annotation.
---
=> Add RetryExtension and OllamaTestFixtureExtension to OllamaAgentIntegrationTest

agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/builder/AIAgentParallelNodesMergeContext.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/builder/AIAgentSubgraphBuilder.kt, agents/agents-core/src/commonTest/kotlin/ai/koog/agents/core/dsl/extension/ParallelNodesMergeContextTest.kt, agents/agents-core/src/commonTest/kotlin/ai/koog/agents/core/dsl/extension/ParallelNodesTest.kt, examples/src/main/kotlin/ai/koog/agents/example/parallelexecution/BestJokeAgent.kt
Edit parallel node execution API:
- Remove transformation (if needed, it could be node inside the node)
- Combine parallel and merge node to one (as they can not leave without each other and make type more complex keeping them separate)
The new approach to define parallel nodes is:
```
val parallelNode by parallel(node1, node2, node3) {
// Merge output and context
selectBy {...}
}
```
=> Pretty API for parallel node execution

.github/workflows/heavy-tests.yml, build.gradle.kts, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/SingleLLMPromptExecutorIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/Models.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/TestUtils.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/build.gradle.kts, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/BedrockToolSerializationTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/BedrockAI21JambaSerializationTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/JambaDataModelsTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/amazon/BedrockAmazonNovaSerializationTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/amazon/NovaDataModelsTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/anthropic/BedrockAnthropicClaudeSerializationTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/meta/BedrockMetaLlamaSerializationTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/meta/LlamaDataModelsTest.kt
1. Added tests for serialization and deserialization of requests to Bedrock from different sub-providers;
2. Added `AWS_SECRET_KEY` and `AWS_ACCESS_KEY_ID` env variables to the environment variables of integration tests' run;
3. Add a test for `simpleBedrockExecutor`.
---
=> AWS Bedrock tests + serialization/deserialization tests for Bedrock providers

agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/entity/AIAgentNode.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/entity/AIAgentSubgraph.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/builder/AIAgentNodeBuilder.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/builder/AIAgentSubgraphBuilder.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryTest.kt, agents/agents-test/src/commonMain/kotlin/ai/koog/agents/testing/feature/TestingFeature.kt, examples/src/main/kotlin/ai/koog/agents/example/parallelexecution/BestJokeAgent.kt
Before the name duplication exception was thrown from, because parallel nodes call not `executeUnsafe` but `execute`, skipping adding naming for the open telemetry
---
=> Fix open telemetry parallel nodes support

prompt/prompt-cache/prompt-cache-files/src/jvmMain/kotlin/ai/koog/prompt/cache/files/FilePromptCache.kt, prompt/prompt-cache/prompt-cache-files/src/jvmTest/kotlin/ai/koog/prompt/cache/files/FilePromptCacheTest.kt, prompt/prompt-cache/prompt-cache-model/build.gradle.kts, prompt/prompt-cache/prompt-cache-model/src/commonMain/kotlin/ai/koog/prompt/cache/memory/InMemoryPromptCache.kt, prompt/prompt-cache/prompt-cache-model/src/commonMain/kotlin/ai/koog/prompt/cache/model/PromptCache.kt, prompt/prompt-cache/prompt-cache-model/src/jvmTest/kotlin/ai/koog/prompt/cache/memory/InMemoryPromptCacheTest.kt, prompt/prompt-cache/prompt-cache-redis/build.gradle.kts, prompt/prompt-cache/prompt-cache-redis/src/jvmMain/kotlin/ai/koog/prompt/cache/redis/RedisPromptCache.kt, prompt/prompt-cache/prompt-cache-redis/src/jvmTest/kotlin/ai/koog/prompt/cache/redis/MockRedisClient.kt, prompt/prompt-cache/prompt-cache-redis/src/jvmTest/kotlin/ai/koog/prompt/cache/redis/RedisPromptCacheTest.kt, prompt/prompt-executor/prompt-executor-cached/build.gradle.kts, prompt/prompt-executor/prompt-executor-cached/src/commonMain/kotlin/ai/koog/prompt/executor/cached/CachedPromptExecutor.kt, prompt/prompt-executor/prompt-executor-cached/src/jvmTest/kotlin/ai/koog/prompt/executor/cached/CachedPromptExecutorTest.kt, prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/message/Message.kt
[JBAI-15068](https://youtrack.jetbrains.com/issue/JBAI-15068)
Fixed prompt to cache key conversion strategy so that the same prompts with different metadata result in the same cache key.
---
=> Fix CachedPromptExecutor / PromptCache so that it works with timestamps correctly

agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/extension/AIAgentLLMActions.kt, agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/dsl/extension/AIAgentNodes.kt, agents/agents-features/agents-features-memory/src/commonMain/kotlin/ai/koog/agents/memory/feature/AgentMemory.kt, agents/agents-features/agents-features-memory/src/commonMain/kotlin/ai/koog/agents/memory/feature/nodes/MemoryNodes.kt
Fixes #288 
Allows to select an optional custom model for fact retrieval from the history in memory nodes and history compression nodes
---
=> #288: Support providing custom LLM for fact retrieval in the history

qodana.yaml
Currently Qodana detects a transitive dependency license coming from spring-boot-web (which is Apache 2.0) as proprietary. 
This fix disables the check on this module
---
=> Ignore license check for koog-spring-boot-starter module to avoid false positive on spring-boot-web

agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/AssistantMessageEvent.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/ChoiceEvent.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/GenAIAgentEvent.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/ModerationResponseEvent.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/SystemMessageEvent.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/ToolMessageEvent.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/UserMessageEvent.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/span/GenAIAgentSpan.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/AssistantMessageEventTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/ChoiceEventTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/EventBodyFieldTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/ModerationResponseEventTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/SystemMessageEventTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/ToolMessageEventTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/UserMessageEventTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/mock/MockGenAIAgentEvent.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/mock/MockLLMProvider.kt, prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/dsl/ModerationAPI.kt
- Body fields should not be fully filtered when verbose is sert to false. It rather should hide the sensitive content. Updated the logic to filter content from Open Telemetry events;
- Add tests to verify the verbose flag for each event and for agent run;
- Fix issue with serializing Moderation Response event for Open Telemetry.
---
=> KG-135. Fix verbose flag behavior for event body fields in Open Telemetry

agents/agents-ext/src/commonMain/kotlin/ai/koog/agents/ext/agent/AIAgentSubgraphExt.kt
Update the descriptor name to `finish_task_execution_result` in AIAgentSubgraphExt to avoid name collision.
---
=> Fix duplicated tool names in AIAgentSubgraphExt

integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/ToolSchemaExecutorIntegrationTest.kt
Cover the cases that weren't yet checked. Found a bug, see https://youtrack.jetbrains.com/issue/KG-185/No-validation-for-an-empty-description-or-tool-parameter-name-on-execution
---
=> Add tests for invalid ToolDescriptor validation

prompt/prompt-llm/src/commonMain/kotlin/ai/koog/prompt/llm/OllamaModels.kt
I returned `llama3.2:latest` tag to `LLAMA_3_2` model, because it turns out if you have `llama3.2:latest` installed and trying to run `llama3.2:3b` it's failing with exception about missing `llama3.2:3b`.
We even experienced it in the tests.
So in order to avoid such confusing behaviour - `LLAMA_3_2` is now `llama3.2:latest`
---
=> Returned llama3.2:latest as default LLAMA_3_2 model

agents/agents-ext/src/commonMain/kotlin/ai/koog/agents/ext/agent/SubgraphWithRetry.kt, agents/agents-ext/src/commonTest/kotlin/ai/koog/agents/ext/agent/SubgraphWithRetryTest.kt
---
[KG-188](https://youtrack.jetbrains.com/issue/KG-188)
Allow to provide condition description and feedback in the retry component.
=> Add the feedback mechanism for the retry component

agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/ToolMessageEvent.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetry.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/span/GenAIAgentSpan.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/OpenTelemetryTestAPI.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/ToolMessageEventTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/mock/MockToolGetWeather.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/span/GenAIAgentSpanTest.kt
Add a list of all messages when creating an inference span
---
=> KG-172. Add all messages to the inference span for Open Telemetry

rag/rag-base/src/commonMain/kotlin/ai/koog/rag/base/files/FileMetadata.kt, rag/rag-base/src/commonMain/kotlin/ai/koog/rag/base/files/FileSystemProvider.kt, rag/rag-base/src/commonMain/kotlin/ai/koog/rag/base/files/FilteredFileSystemProvider.kt, rag/rag-base/src/jvmMain/kotlin/ai/koog/rag/base/files/JVMFileSystemProvider.kt, rag/rag-base/src/jvmTest/kotlin/ai/koog/rag/base/files/JVMFileSystemProviderTest.kt, rag/vector-storage/src/commonTest/kotlin/ai/koog/rag/vector/FileDocumentEmbeddingStorageTest.kt, rag/vector-storage/src/commonTest/kotlin/ai/koog/rag/vector/FileVectorStorageTest.kt, rag/vector-storage/src/commonTest/kotlin/ai/koog/rag/vector/TextFileDocumentEmbeddingStorageTest.kt, rag/vector-storage/src/commonTest/kotlin/ai/koog/rag/vector/mocks/MockDocumentProviders.kt
1. Extracted `content` into a separate method to make `metadata` and `isFile/isDirectory` faster.
2. Renamed `FileContent` to `FileContentType` to better reflect its purpose.
3. Covered the new method with tests.
4. Fixed typo in `MockFileSystemProvider` name.
~~**QUESTION 1** Please take a look at `getFileContentType` in `FilteredFileSystemProvider` and in~~ ~~`FileSystemProvider`. Should we make the return type nullable and use the same check as for `metadata`?~~
~~```~~
~~return if (filter.show(path, fs)) {~~
~~    fs.getFileContentType(path)~~
~~} else {~~
~~    null~~
~~}~~
~~```~~
~~Now it uses `requireAllowed(path)`.~~
~~**QUESTION 2** Should I just get rid of `Path.contentType()` and inline its logic in `getFileContentType` since it's~~ ~~the~~ only place where it's used and move …
=> Extract content metadata into a separate method

agents/agents-features/agents-features-memory/src/commonMain/kotlin/ai/koog/agents/memory/providers/LocalFileMemoryProvider.kt, agents/agents-features/agents-features-memory/src/commonMain/kotlin/ai/koog/agents/memory/storage/Storage.kt, agents/agents-features/agents-features-memory/src/jvmTest/kotlin/ai/koog/agents/memory/storage/JvmStorageTest.kt, agents/agents-features/agents-features-snapshot/src/commonMain/kotlin/ai/koog/agents/snapshot/providers/file/FilePersistencyStorageProvider.kt, rag/rag-base/src/commonMain/kotlin/ai/koog/rag/base/files/Extensions.kt, rag/rag-base/src/commonMain/kotlin/ai/koog/rag/base/files/FileSystemProvider.kt, rag/rag-base/src/commonMain/kotlin/ai/koog/rag/base/files/FilteredFileSystemProvider.kt, rag/rag-base/src/jvmMain/kotlin/ai/koog/rag/base/files/JVMFileSystemProvider.kt, rag/rag-base/src/jvmTest/kotlin/ai/koog/rag/base/files/JVMFileSystemProviderTest.kt, rag/rag-base/src/jvmTest/kotlin/ai/koog/rag/base/files/JVMFilteredFileSystemProviderTest.kt, rag/vector-storage/src/commonMain/kotlin/ai/koog/rag/vector/FileVectorStorage.kt, rag/vector-storage/src/commonTest/kotlin/ai/koog/rag/vector/FileDocumentEmbeddingStorageTest.kt, rag/vector-storage/src/commonTest/kotlin/ai/koog/rag/vector/TextFileDocumentEmbeddingStorageTest.kt, rag/vector-storage/src/commonTest/kotlin/ai/koog/rag/vector/mocks/MockDocumentProviders.kt
=> Reworked FileSystemProvider

agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/AssistantMessageEvent.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/ChoiceEvent.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/EventBodyFields.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/SystemMessageEvent.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/ToolMessageEvent.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/UserMessageEvent.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetry.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/AssistantMessageEventTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/ChoiceEventTest.kt
Add a tool arguments to Open Telemetry event and updated test (#462)
---
=> Add tool arguments for gen_ai.choice and gen_ai.assistant.message events (#462)

prompt/prompt-llm/src/commonMain/kotlin/ai/koog/prompt/llm/LLMCapability.kt
=> Fix typo in docs for Completion LLM Capability 

agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/attribute/SpanAttributes.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetry.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/span/ExecuteToolSpan.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryTest.kt
Add `input.value` and `output.value` attributes for `ExecuteToolSpan` span in OpenTelemetry support
---
=> KG-175. Add input.value and output.value attributes for ExecuteToolSpan

prompt/prompt-executor/prompt-executor-clients/prompt-executor-anthropic-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/anthropic/AnthropicLLMClient.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-anthropic-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/anthropic/DataModel.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-anthropic-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/anthropic/AnthropicModelsTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/BedrockAI21JambaSerialization.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/JambaDataModel.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/amazon/BedrockAmazonNovaSerialization.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/amazon/NovaDataModels.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmMain/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/anthropic/BedrockAnthropicClaudeSerialization.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/BedrockAI21JambaSerializationTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/ai21/JambaDataModelsTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/amazon/BedrockAmazonNovaSerializationTest.kt, prompt/prompt-executor/prompt-executor-clients/prompt-executor-bedrock-client/src/jvmTest/kotlin/ai/koog/prompt/executor/clients/bedrock/modelfamilies/anthropic/BedrockAnthropicClaudeSerializationTest.kt, prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/params/LLMParams.kt
Add `maxTokens` to prompt parameters so user can configure
Fixes: https://youtrack.jetbrains.com/issue/KG-129
---
=> Add maxTokens as prompt parameters

docs/docs/prompt-api.md, prompt/prompt-executor/Module.md, prompt/prompt-executor/prompt-executor-clients/Module.md, prompt/prompt-executor/prompt-executor-clients/build.gradle.kts, prompt/prompt-executor/prompt-executor-clients/src/commonMain/kotlin/ai/koog/prompt/executor/clients/retry/RetryConfig.kt, prompt/prompt-executor/prompt-executor-clients/src/commonMain/kotlin/ai/koog/prompt/executor/clients/retry/RetryingLLMClient.kt, prompt/prompt-executor/prompt-executor-clients/src/commonTest/kotlin/ai/koog/prompt/executor/clients/retry/RetryConfigTest.kt, prompt/prompt-executor/prompt-executor-clients/src/commonTest/kotlin/ai/koog/prompt/executor/clients/retry/RetryingLLMClientTest.kt
Real world agent usage is facing multiple provider connectivity issues: timeouts, rate limits (especially during parallel agents execution), network and backend issues. To make agents more resilient, retry logic possibility should be added. This change introduces an LLM clients decorator supporting configurable retry logic. 
Issue: https://youtrack.jetbrains.com/issue/KG-235/Introduce-Retry-logic-for-LLM-clients
---
=> Introduce Retry logic for LLM clients

README.md, docs/docs/index.md
When using Maven to add Koog dependencies, `-jvm` platform postifx has to be explicitly specified, because in general `pom.xml` file all scopes are set to `runtime`, which leads to compilation errors.  This is by design when publishing KMP artifacts with Gradle, it expects consumers to use richer Gradle-specific metadata file, so for Maven platform has to be specified explicitly.
Fixes #583
=> [docs] Update docs with proper Maven dependency example

agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/event/EventBodyField.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/event/EventBodyFieldTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/extension/EventBodyFieldExtTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryTest.kt
See https://youtrack.jetbrains.com/issue/KG-268/Assistant-tool-calls-in-OTEL-traces-of-are-not-valid-JSONs
No
---
=> KG-268 EventBodyField for function call is valid JSON

agents/agents-tools/build.gradle.kts, agents/agents-tools/src/commonMain/kotlin/ai/koog/agents/file/tools/ReadFileTool.kt, agents/agents-tools/src/commonMain/kotlin/ai/koog/agents/file/tools/model/FileSize.kt, agents/agents-tools/src/commonMain/kotlin/ai/koog/agents/file/tools/model/FileSystemEntry.kt, agents/agents-tools/src/commonMain/kotlin/ai/koog/agents/file/tools/render/Text.kt, agents/agents-tools/src/commonTest/kotlin/ai/koog/agents/file/tools/model/FileSizeTest.kt, agents/agents-tools/src/commonTest/kotlin/ai/koog/agents/file/tools/model/FileSystemEntryTest.kt, agents/agents-tools/src/commonTest/kotlin/ai/koog/agents/file/tools/render/TextTest.kt, agents/agents-tools/src/jvmTest/kotlin/ai/koog/agents/file/tools/ReadFileToolJvmTest.kt, agents/agents-tools/src/jvmTest/kotlin/ai/koog/agents/file/tools/model/FileSystemEntryJvmTest.kt, docs/docs/built-in-tools.md
This change extracts `ReadFileTool` from CE, simplifies it, and adds tests. It reads file content, either the whole file or a 0 based [start, end) slice, and returns file metadata and the extracted content.
Issue: https://youtrack.jetbrains.com/issue/KG-227/CodeAgent-OSS.-Step-1
---
=> Add ReadFileTool to read file content

prompt/prompt-executor/prompt-executor-clients/prompt-executor-google-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/google/GoogleModels.kt
bug - Koog presents the error "Model gemini-2.5-flash does not support tools" when using tools with gemini-2.5-flash
fix - update gemini-2.5-flash to support all capabilities 
---
=> fix: add function calling for gemini-2.5-flash

prompt/prompt-executor/prompt-executor-clients/prompt-executor-openai-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/openai/structure/OpenAIStandardJsonSchemaGenerator.kt, prompt/prompt-structure/src/commonMain/kotlin/ai/koog/prompt/structure/json/JsonStructuredData.kt, prompt/prompt-structure/src/commonMain/kotlin/ai/koog/prompt/structure/json/generator/BasicJsonSchemaGenerator.kt, prompt/prompt-structure/src/commonMain/kotlin/ai/koog/prompt/structure/json/generator/GenericJsonSchemaGenerator.kt, prompt/prompt-structure/src/commonMain/kotlin/ai/koog/prompt/structure/json/generator/JsonSchemaGenerator.kt, prompt/prompt-structure/src/commonMain/kotlin/ai/koog/prompt/structure/json/generator/StandardJsonSchemaGenerator.kt, prompt/prompt-structure/src/commonTest/kotlin/ai/koog/prompt/structure/json/generator/JsonSchemaGeneratorTest.kt
Fixes #377 
Changes are the same as #378, it's just the updated version after the refactor of #443
Proposed changes:
Add an `excludedProperties` parameter like this:
```kotlin
simpleSchemaGenerator.generate(
"TestClass",
serializer<TestClass>(),
descriptionOverrides = emptyMap(),
excludedProperties = setOf("TestClass.someProperty")
)
```
---
=> Add support for excluding properties in JSON schema generation

gradle/libs.versions.toml, prompt/prompt-executor/prompt-executor-llms/build.gradle.kts, prompt/prompt-executor/prompt-executor-llms/src/commonTest/kotlin/ai/koog/prompt/executor/llms/MockOpenAILLMClient.kt, prompt/prompt-executor/prompt-executor-llms/src/commonTest/kotlin/ai/koog/prompt/executor/llms/MultiLLMPromptExecutorTest.kt, prompt/prompt-executor/prompt-executor-llms/src/jvmMain/kotlin/ai/koog/prompt/executor/llms/Executors.kt, prompt/prompt-executor/prompt-executor-llms/src/jvmTest/java/ai/koog/prompt/executor/llms/ExecutorsTest.java, prompt/prompt-executor/prompt-executor-model/build.gradle.kts, prompt/prompt-executor/prompt-executor-model/src/jvmMain/kotlin/ai/koog/prompt/executor/model/JavaPromptExecutor.kt, prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/dsl/Prompt.kt, prompt/prompt-model/src/commonMain/kotlin/ai/koog/prompt/message/Message.kt, test-utils/build.gradle.kts
Add Java-compatible prompt executor and refactor tests to mock OpenAI client
Calling Koog Api from Java is not easy because of Coroutines API (KG-312)
**NB! Supports only non-streaming API yet**. Streaming api will be supported in the separate PR
- Introduced `JavaPromptExecutor` to expose a Java-friendly API for prompt execution. 
- Enhanced `Prompt` and `Message` data classes with `@JvmOverloads` for improved interop with Java.
- Moved mock OpenAI client (`MockOpenAILLMClient`) for unit testing prompt execution.
- Updated `build.gradle.kts` to include new dependencies: Mockito and AssertJ.
- Refactored `MultiLLMPromptExecutorTest` to reuse mock OpenAI client with configurable `Clock`.
---
=> KG-312 Add Java-compatible prompt executor (non-streaming)

agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/attribute/SpanAttributes.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetry.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/integration/Utils.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/integration/weave/WeaveSpanAdapter.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/span/GenAIAgentSpan.kt, agents/agents-features/agents-features-opentelemetry/src/jvmMain/kotlin/ai/koog/agents/features/opentelemetry/span/InferenceSpan.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/OpenTelemetryTestAPI.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/feature/OpenTelemetryTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/integration/TraceStructureTestBase.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/integration/UtilsTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/integration/langfuse/LangfuseTraceStructureTest.kt, agents/agents-features/agents-features-opentelemetry/src/jvmTest/kotlin/ai/koog/agents/features/opentelemetry/integration/weave/WeaveTraceStructureTest.kt
[KG-162](https://youtrack.jetbrains.com/issue/KG-162/Support-tokens-span-attributes-in-Koog-events-Open-Telemetry-spans). Add information about tokens usage in Open Telemetry feature spans.
- Add tokens usage statistics for OpenTelemetry feature;
- Update Langfuse and Weave exporters for OTel;
- Add tests to verify output tokens attributes.
Open Telemetry feature needs to have usage statistics about input and output tokens. It can help to evaluate agents execution better.
No
---
=> KG-162. Add tokens usage information for inference span in OTel

agents/agents-core/src/commonMain/kotlin/ai/koog/agents/core/agent/entity/AIAgentStorage.kt, agents/agents-features/agents-features-snapshot/src/commonMain/kotlin/ai/koog/agents/snapshot/feature/Persistency.kt
There's an issue in `AIAgentStorage` implementation where `AIAgentStorageKey` is incorrectly defined as a data class. This causes keys with identical names to be treated as equal due to auto-generated equals/hashCode methods, contradicting the documented behavior that each key instance should be unique regardless of name.
The fix is straightforward - remove the data modifier from the class definition. This ensures storage keys are compared by instance identity rather than content equality.
=> [agents] Make `AIAgentStorageKey` in agent storage actually unique by removing `data` modifier

.github/workflows/heavy-tests.yml, agents/agents-test/src/commonMain/kotlin/ai/koog/agents/testing/tools/DummyAIAgentContext.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/agent/AIAgentIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/agent/AIAgentMultipleLLMIntegrationTest.kt, integration-tests/src/jvmTest/kotlin/ai/koog/integration/tests/utils/RetryUtils.kt, integration-tests/src/jvmTest/resources/simplelogger.properties, prompt/prompt-executor/prompt-executor-clients/prompt-executor-google-client/src/commonMain/kotlin/ai/koog/prompt/executor/clients/google/DataModel.kt
Some fixes to revive the integration tests.
1. Relax some assertions as the amount of reasoning is not a determined number;
2. Remove an extensive event handler in Agent integration tests where it wasn't used;
3. Parallelize the execution of `executor` test suite;
4. Filter our `tombstone` checkpoints that were causing test failures (now we count only user checkpoints);
5. Add a test for agent with tools in a subgraph only (and for wrapping an error when the tools aren't registered);
6. Add error 500 from Anthropic to the list of 3-rd parties (won't cause test failure anymore);
7. Reduce extensive logging in the tests;
8. Make `promptTokenCount` and `totalTokenCount` nullable for Gemini models (as sometimes they're not returned in the LLM error answers).
❗ `promptTokenCount` and …
=> Revive and parallelize integration tests

docs/docs/opentelemetry-langfuse-exporter.md, docs/docs/opentelemetry-support.md, docs/docs/opentelemetry-weave-exporter.md
Added notes that `setVerbose` needs to be set to true when installing/configuring the OpenTelemetry feature if the user wants to see LLM message content in Langfuse. Otherwise, message content shows up as `HIDDEN:non-empty` in Langfuse.
Changes added to the following pages and sections:
https://docs.koog.ai/opentelemetry-support/#setverbose
https://docs.koog.ai/opentelemetry-langfuse-exporter/#what-gets-traced
Based on feedback from users.
None.
---
=> KG-428 Document setVerbose(true) for message visibility in Langfuse

docs/docs/koog-slack-channel.md, docs/mkdocs.yml, docs/overrides/partials/header.html
Created a page that opens when users click the Slack icon on the documentation website. 
The page explains that the Koog channel is part of the Kotlin Slack workspace and provides instructions for users who already have a Kotlin Slack account and those who don’t.
---
=> Update Slack link and add Koog Slack channel documentation
